# Generated by Django 5.0.6 on 2024-06-14 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_field', models.FloatField()),
                ('name', models.CharField(max_length=254)),
                ('structure', models.CharField(max_length=254)),
                ('use', models.CharField(max_length=254)),
                ('no_floors', models.FloatField()),
                ('rooms', models.FloatField()),
                ('capacity', models.CharField(max_length=254)),
                ('stracture', models.CharField(max_length=254)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
